.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. compagnies

.. _Current Designs: https://www.curdes.com/
.. _SPL: https://spl.audio/en/
.. _SR Research: https://www.sr-research.com/


.. datasets

.. _sample dataset: https://github.com/fcbg-platforms/meg-wiki-datasets/tree/main
.. _sample dataset ssp: https://github.com/fcbg-platforms/meg-wiki-datasets/tree/main/ssp


.. devices

.. _Chronos: https://pstnet.com/products/chronos/
.. _Crimson 3: https://spl.audio/en/spl-produkt/crimson-3/
.. _current-designs response-devices: https://www.curdes.com/mainforp/responsedevices.html
.. _Digitimer: https://www.digitimer.com/
.. _DS7A: https://www.digitimer.com/product/human-neurophysiology/peripheral-stimulators/ds7a-ds7ah-hv-current-stimulator/
.. _EyeLink 1000 Plus: https://www.sr-research.com/eyelink-1000-plus/
.. _LEAD108C: https://www.biopac.com/product/clip-leads-rt/
.. _MEGIN Triux Neo: https://megin.com/triux-neo/
.. _MEGIN product data: https://megin.com/wp-content/uploads/2022/01/MEGIN-TRIUX-neo-Product-Data-2021.pdf
.. _Optimic MEG microphone: https://www.optoacoustics.com/medical/optimic-meg-microphone
.. _Opto acoustics: https://www.optoacoustics.com/
.. _Pneumatic Squeeze Ball: https://www.curdes.com/mainforp/responsedevices/hhsc-1x1-pne.html
.. _Polhemus: https://polhemus.com/motion-tracking/all-trackers/fastrak/
.. _ProPixx projector: https://vpixx.com/products/propixx-mri/
.. _SoundPixx: https://vpixx.com/products/soundpixx/
.. _TIP-300: https://natuscrmprod.my.site.com/usa/s/product/detail/01t5w00000FVqgrAAD
.. _X-Rite i1Display Pro colorimeter: https://vpixx.com/products/x-rite-i1display/
.. _932 interface: https://www.curdes.com/mainforp/interfaces/fiu-932b.html
.. _4 button (curve left): https://www.curdes.com/mainforp/responsedevices/hhsc-1x4-cl.html
.. _8 button bimanual (curved lines): https://www.curdes.com/mainforp/responsedevices/hhsc-2x4-c.html


.. glossary

.. _LRPA: https://www.fieldtriptoolbox.org/faq/how_are_the_lpa_and_rpa_points_defined/
.. _MNE's background on projectors and projections: https://mne.tools/stable/auto_tutorials/preprocessing/45_projectors_background.html
.. _MNE's background on SSS and Maxwell filtering: https://mne.tools/stable/auto_tutorials/preprocessing/60_maxwell_filtering_sss.html#background-on-sss-and-maxwell-filtering
.. _Nasion: https://en.wikipedia.org/wiki/Nasion
.. _rst: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html
.. _spherical harmonics: https://en.wikipedia.org/wiki/Spherical_harmonics


.. IT

.. _intel Xeon W-2245: https://www.intel.com/content/www/us/en/products/sku/198609/intel-xeon-w2245-processor-16-5m-cache-3-90-ghz/specifications.html
.. _Nvidia Quadro P2200: https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro-product-literature/quadro-p2200-datasheet-letter-974207-r4-web.pdf
.. _TP-Link TG-3468: https://www.tp-link.com/us/home-networking/pci-adapter/tg-3468/


.. others

.. _calpendo: https://campusbiotech.calpendo.com/


.. project

.. _MIT license: https://opensource.org/licenses/MIT
.. _project github: https://github.com/fcbg-platforms/meg-wiki
.. _project github doc: https://github.com/fcbg-platforms/meg-wiki/tree/main/doc
.. _project issue tracker: https://github.com/fcbg-platforms/meg-wiki/issues
.. _project license: https://github.com/fcbg-platforms/meg-wiki/blob/main/LICENSE


.. software

.. _autoreject: https://autoreject.github.io/stable/index.html
.. _byte-triggers: https://fcbg-platforms.github.io/byte-triggers/
.. _E-Prime: https://pstnet.com/products/e-prime/
.. _eyelink-track: https://github.com/fcbg-platforms/eyelink-track
.. _furo: https://pradyunsg.me/furo/
.. _mne stable: https://mne.tools/stable/index.html
.. _mne bids: https://mne.tools/mne-bids/stable/index.html
.. _mne connectivity: https://mne.tools/mne-connectivity/stable/index.html
.. _mne icalabel: https://mne.tools/mne-icalabel/stable/index.html
.. _numpy: https://numpy.org/
.. _pre-commit: https://pre-commit.com/
.. _psychopy: https://www.psychopy.org/
.. _psychtoolbox: http://psychtoolbox.org/
.. _scikit-learn: https://scikit-learn.org/stable/
.. _scipy: https://scipy.org/
.. _spec 0: https://scientific-python.org/specs/spec-0000/
.. _sphinx-gallery: https://sphinx-gallery.github.io/stable/index.html
